services:
  web:
    ports:
      - 3030:8080
    image: herrsorgenfrei/boothello
    networks:
      - boothello
  get:
    image: alpine/curl
    command: web:8080/api/helloworld/name
    depends_on:
      - web
    networks:
      - boothello

networks:
  boothello:
    driver: bridge
