services:
  web:
    ports:
      - 3030:8080
    image: herrsorgenfrei/boothello
    networks:
      - boothello
  get:
    image: alpine/curl
    command: "curl web:3000/api/helloworld/name"
    ports:
      - 8080:3030
    depends_on:
      - web
    networks:
      - boothello

networks:
  boothello:
    driver: bridge